// Code generated by moshi-kotlin-codegen. Do not edit.
package edsl.model

import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonDataException
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.Types
import edsl.KeyValuePair
import java.lang.NullPointerException
import kotlin.String
import kotlin.collections.MutableList

class ExecutionDefinitionJsonAdapter(moshi: Moshi) : JsonAdapter<ExecutionDefinition>() {
    private val options: JsonReader.Options = JsonReader.Options.of("executionsParams")

    private val mutableListOfKeyValuePairOfStringStringAdapter: JsonAdapter<MutableList<KeyValuePair<String, String>>> =
            moshi.adapter<MutableList<KeyValuePair<String, String>>>(Types.newParameterizedType(MutableList::class.java, Types.newParameterizedType(KeyValuePair::class.java, String::class.java, String::class.java)), kotlin.collections.emptySet(), "executionsParams")

    override fun toString(): String = "GeneratedJsonAdapter(ExecutionDefinition)"

    override fun fromJson(reader: JsonReader): ExecutionDefinition {
        var executionsParams: MutableList<KeyValuePair<String, String>>? = null
        reader.beginObject()
        while (reader.hasNext()) {
            when (reader.selectName(options)) {
                0 -> executionsParams = mutableListOfKeyValuePairOfStringStringAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'executionsParams' was null at ${reader.path}")
                -1 -> {
                    // Unknown name, skip it.
                    reader.skipName()
                    reader.skipValue()
                }
            }
        }
        reader.endObject()
        var result = ExecutionDefinition(
                executionsParams = executionsParams ?: throw JsonDataException("Required property 'executionsParams' missing at ${reader.path}"))
        return result
    }

    override fun toJson(writer: JsonWriter, value: ExecutionDefinition?) {
        if (value == null) {
            throw NullPointerException("value was null! Wrap in .nullSafe() to write nullable values.")
        }
        writer.beginObject()
        writer.name("executionsParams")
        mutableListOfKeyValuePairOfStringStringAdapter.toJson(writer, value.executionsParams)
        writer.endObject()
    }
}
