// Code generated by moshi-kotlin-codegen. Do not edit.
package edsl.model

import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonDataException
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import java.lang.NullPointerException
import kotlin.String

class RelationJsonAdapter(moshi: Moshi) : JsonAdapter<Relation>() {
    private val options: JsonReader.Options = JsonReader.Options.of("name", "schemaName", "schema")

    private val stringAdapter: JsonAdapter<String> =
            moshi.adapter<String>(String::class.java, kotlin.collections.emptySet(), "name")

    override fun toString(): String = "GeneratedJsonAdapter(Relation)"

    override fun fromJson(reader: JsonReader): Relation {
        var name: String? = null
        var schemaName: String? = null
        var schema: String? = null
        reader.beginObject()
        while (reader.hasNext()) {
            when (reader.selectName(options)) {
                0 -> name = stringAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'name' was null at ${reader.path}")
                1 -> schemaName = stringAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'schemaName' was null at ${reader.path}")
                2 -> schema = stringAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'schema' was null at ${reader.path}")
                -1 -> {
                    // Unknown name, skip it.
                    reader.skipName()
                    reader.skipValue()
                }
            }
        }
        reader.endObject()
        var result = Relation(
                name = name ?: throw JsonDataException("Required property 'name' missing at ${reader.path}"))
        result = result.copy(
                schemaName = schemaName ?: result.schemaName,
                schema = schema ?: result.schema)
        return result
    }

    override fun toJson(writer: JsonWriter, value: Relation?) {
        if (value == null) {
            throw NullPointerException("value was null! Wrap in .nullSafe() to write nullable values.")
        }
        writer.beginObject()
        writer.name("name")
        stringAdapter.toJson(writer, value.name)
        writer.name("schemaName")
        stringAdapter.toJson(writer, value.schemaName)
        writer.name("schema")
        stringAdapter.toJson(writer, value.schema)
        writer.endObject()
    }
}
