// Code generated by moshi-kotlin-codegen. Do not edit.
package edsl.model

import com.squareup.moshi.JsonAdapter
import com.squareup.moshi.JsonDataException
import com.squareup.moshi.JsonReader
import com.squareup.moshi.JsonWriter
import com.squareup.moshi.Moshi
import com.squareup.moshi.Types
import edsl.KeyValuePair
import java.lang.NullPointerException
import kotlin.String
import kotlin.collections.List

class StartupCommandJsonAdapter(moshi: Moshi) : JsonAdapter<StartupCommand>() {
    private val options: JsonReader.Options = JsonReader.Options.of("params")

    private val listOfKeyValuePairOfStringStringAdapter: JsonAdapter<List<KeyValuePair<String, String>>> =
            moshi.adapter<List<KeyValuePair<String, String>>>(Types.newParameterizedType(List::class.java, Types.newParameterizedType(KeyValuePair::class.java, String::class.java, String::class.java)), kotlin.collections.emptySet(), "params")

    override fun toString(): String = "GeneratedJsonAdapter(StartupCommand)"

    override fun fromJson(reader: JsonReader): StartupCommand {
        var params: List<KeyValuePair<String, String>>? = null
        reader.beginObject()
        while (reader.hasNext()) {
            when (reader.selectName(options)) {
                0 -> params = listOfKeyValuePairOfStringStringAdapter.fromJson(reader) ?: throw JsonDataException("Non-null value 'params' was null at ${reader.path}")
                -1 -> {
                    // Unknown name, skip it.
                    reader.skipName()
                    reader.skipValue()
                }
            }
        }
        reader.endObject()
        var result = StartupCommand()
        result = StartupCommand(
                params = params ?: result.params)
        return result
    }

    override fun toJson(writer: JsonWriter, value: StartupCommand?) {
        if (value == null) {
            throw NullPointerException("value was null! Wrap in .nullSafe() to write nullable values.")
        }
        writer.beginObject()
        writer.name("params")
        listOfKeyValuePairOfStringStringAdapter.toJson(writer, value.params)
        writer.endObject()
    }
}
